---
- name: "Install PostgreSQL repo"
  yum:
    name: "{{ postgresql_repo }}"
    state: present

- name: "Install PostgreSQL packages"
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ postgresql_packages }}"  

- name: "Create PostgreSQL data directory"
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "postgres"
    group: "postgres"
    state: directory
    mode: 0700

- name: "Check if PostgreSQL database is initialized"
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: "PostgreSQL database is initialized"
  command: "{{ postgresql_bin_path }}/postgresql-{{ postgresql_version }}-setup initdb"
  become: true
  when: not pgdata_dir_version.stat.exists

- name: "Started PostgreSQL"
  service:
    name: "postgresql-{{ postgresql_version }}"
    state: "restarted"
    enabled: "yes"