---
- name: "Install postgresql repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ postgresql_repo }}"

- name: "Install PostgreSQL packages"
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ postgresql_packages }}"  

- name: "Set PostgreSQL environment variables".
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644