---
- name: "Install postgresql repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ postgresql_repo }}"

- name: "Install PostgreSQL packages"
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ postgresql_packages }}"  